### ISSUE TITLE
The setup doesn't seem to find my python installed

### ISSUE THREAD

**Issue by RLArt2022** [sdfxai/sdfx#3]
I have python 3.11.0 installed, but when running the setup.bat 

`Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
The system cannot find the path specified.` 

is the error it shows. 

Using win11, I do not have store installed anymore, so cannot install python that way.

**Comment by Gushousekai195** [comment]
Same issue but I'm on Win10. My python instance was installed manually.

**Comment by BenDes21** [comment]
same issue

**Comment by MrKuenning** [comment]
I ran into this error also. I got around it by changing the setup bat to this.

``` bat
@echo off

python -m venv .venv
call .venv\Scripts\activate

python setup.py %*

pause
```

**Comment by RLArt2022** [comment]
> I ran into this error also. I got around it by changing the setup bat to this.
> 
> ```batchfile
> @echo off
> 
> python -m venv .venv
> call .venv\Scripts\activate
> 
> python setup.py %*
> 
> pause
> ```

That got me further, thanks. After that I had to put git and nodjs on my path, then it installed. Appreciate the great tip.

**Comment by spartanz51** [comment]
It seems that your Python wasn't added to the Windows environment variables during installation. That's why the setup script can't find Python in your setup
When installing Python, the checkbox to add it to the environment variables should be checked;[ I've added this instruction to the Windows documentation](https://github.com/sdfxai/sdfx?tab=readme-ov-file#windows)

Additionally, I've still added in https://github.com/sdfxai/sdfx/commit/d1788fe181fb6705ed8ff73b2e9cb8100cd3dcf5 a small fallback in the setup script to attempt to determine the Python executable path automatically, taking into account [feedback from Reddit users](https://www.reddit.com/r/StableDiffusion/comments/1c1hisd/comment/kz5ox8n/)

**Comment by spartanz51** [comment]
It seems that your Python wasn't added to the Windows environment variables during installation. That's why the setup script can't find Python in your setup
When installing Python, the checkbox to add it to the environment variables should be checked;[ I've added this instruction to the Windows documentation](https://github.com/sdfxai/sdfx?tab=readme-ov-file#windows)

Additionally, I've still added in https://github.com/sdfxai/sdfx/commit/d1788fe181fb6705ed8ff73b2e9cb8100cd3dcf5 a small fallback in the setup script to attempt to determine the Python executable path automatically, taking into account [feedback from Reddit users](https://www.reddit.com/r/StableDiffusion/comments/1c1hisd/comment/kz5ox8n/)
